apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
spec:
  selector:
    matchLabels:
      name: logger
  template:
    metadata:
      labels:
        name: logger
    spec:
      containers:
      - name: logger
        image: localhost:5000/logger:1.0.5
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DATADOG_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog
                key: api_key
          - name: LOG_PATH
            value: /var/log/containers/hello*.log
          - name: SERVICE_NAME
            value: "hello-world"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
  